### ISSUE TITLE
DAMS.geocode()でSegmentation faultが発生する

### ISSUE THREAD

**Issue by mynkit** [hottolink/pydams#3]
READMEの通り環境構築しましたが，DAMS.geocode()でSegmentation faultが発生してしまいました．．

環境はdockerサーバですのでそちら起因の可能性もありますが，念の為記載させていただきます．

`Dockerfile`
```
FROM python:3.6
USER root

RUN apt-get update
RUN apt-get -y install locales && \
    localedef -f UTF-8 -i ja_JP ja_JP.UTF-8
ENV LANG ja_JP.UTF-8
ENV LANGUAGE ja_JP:ja
ENV LC_ALL ja_JP.UTF-8
ENV TZ JST-9
ENV TERM xterm

RUN apt-get install -y vim less
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install --upgrade Cython
```

` docker-compose.yml`
```
version: '3'
services:
  python36:
    restart: always
    build: .
    container_name: 'python36'
    working_dir: '/root/'
    tty: true
    volumes:
      - ./opt:/root/opt
```
